### ISSUE TITLE
Windows build linking warning?

### ISSUE THREAD

**Issue by matkuki** [mneuroth/QuickScintilla#2]
Hi @mneuroth,

I'm trying to build the code on Windows 10 and am getting these errors:
```
LINK : warning LNK4217: symbol '??0ScintillaEditBase@@QEAA@PEAVQQuickItem@@@Z (public: __cdecl ScintillaEditBase::ScintillaEditBase(class QQuickItem *))' defined in 'ScintillaEditBase.lib(ScintillaEditBase.obj)' is imported by 'main.obj' in function '"public: __cdecl QQmlPrivate::QQmlElement<class ScintillaEditBase>::QQmlElement<class ScintillaEditBase>(void)" (??0?$QQmlElement@VScintillaEditBase@@@QQmlPrivate@@QEAA@XZ)'
LINK : warning LNK4217: symbol '??1ScintillaEditBase@@UEAA@XZ (public: virtual __cdecl ScintillaEditBase::~ScintillaEditBase(void))' defined in 'ScintillaEditBase.lib(ScintillaEditBase.obj)' is imported by 'main.obj' in function '"public: virtual __cdecl QQmlPrivate::QQmlElement<class ScintillaEditBase>::~QQmlElement<class ScintillaEditBase>(void)" (??1?$QQmlElement@VScintillaEditBase@@@QQmlPrivate@@UEAA@XZ)'
LINK : warning LNK4217: symbol '?staticMetaObject@ScintillaEditBase@@2UQMetaObject@@B (public: static struct QMetaObject const ScintillaEditBase::staticMetaObject)' defined in 'ScintillaEditBase.lib(moc_ScintillaEditBase.obj)' is imported by 'main.obj' in function '"int __cdecl qmlRegisterType<class ScintillaEditBase>(char const *,int,int,char const *)" (??$qmlRegisterType@VScintillaEditBase@@@@YAHPEBDHH0@Z)'
```
Any ideas what the problem is?

The executable builds, but when running it I get:
![image](https://user-images.githubusercontent.com/10289651/180253264-4a2aa274-1cf9-4057-84f3-fab421564601.png)

**Comment by matkuki** [comment]
I tried compiling it with Qt6 and MSVC_x64 and that also gives a lot of LINK errors, but when running the executable, I get this:
![image](https://user-images.githubusercontent.com/10289651/180302959-06c0c324-abbf-4aee-b183-4725b7a817f0.png)

**Comment by mneuroth** [comment]
Hi matkuki,

unfortunately QuickScintilla (and SciteQt) supports currently only Qt 5 and is not ported to Qt 6 yet. Please switch to Qt 5 and try it again.

Regards, 
Michael

**Comment by matkuki** [comment]
Thank you for the hint @mneuroth, I got it to build and run with **_Qt5_** and **_Qt Creator 4.11.0_**:
![image](https://user-images.githubusercontent.com/10289651/180572058-ab763b65-4367-479f-88fd-d2a5bfc0a327.png)
Thanks again 👍👍👍

**Comment by mneuroth** [comment]
Hi matkuki,

I added support for QuickScintilla for Qt 6. The Demo app needs at least Qt 6.3.x. Maybe you can test it if it works for you. Feedback is welcome.

Regards,
Michael

**Comment by matkuki** [comment]
Hey @mneuroth,

Thanks for the upgrade, it works with **_Qt6.3.1_** and **_Qt Creator 7.0.2_**:
![image](https://user-images.githubusercontent.com/10289651/180614559-ee32386c-2e03-4ba8-97e6-5bfc59aeede0.png)
